### PR TITLE
Merge test drive and development branches

### PR DESCRIPTION
**Pull request by gryglbrt**
Adding support for db credentials and aws kinesis tier one storage to the dev branch

### CODE REVIEW

**Comment by lsloan** [comment]
Hi, @gryglbrt & @cblaze22.  I realize I'm coming a bit late to the game, but I wonder why these classes were removed from the development branch:

src/main/java/org/apereo/openlrs/storage/redis/RedisPubSubConfig.java
src/main/java/org/apereo/openlrs/storage/redis/RedisPubSubTierOneStorage.java

Aren't they needed for using Redis as tier one storage?  They were available in the old "caliper" branch of the repo and we were using them in our dev environment and the new prod environment we've been working on.

**Comment by gryglbrt** [comment]
Hi @lsloan Yes definitely needed and will be back in shortly. My bad. Was trying to manage a few of these big merges over the holidays and didn't wrap it up in time. Look for everything to be back in the right place by end of day tomorrow.

**Comment by lsloan** [comment]
Sounds good!  @bkirschn and I will be happy to see the changes.

Today I was trying to get a copy of OpenLRS from the "development" branch
to work in our AWS environment.  It would work with the stock
`application.properties` file, using the memory-based storage, but when I
tried to make it work with the redis/mongo configuration we had used with
the "caliper" branch code, it would show a ton of error messages.  Most of
them seem to be about creating the `NormalizedMongoTierTwoStorage` bean.
As I was trying to make sense of the error messages, I noticed that those
Redis classes were gone.  I didn't see any errors about the missing Redis
classes, but that's probably because the Mongo problems were masking them.
I bet as soon as the Mongo problems are fixed the Redis errors would have
shown up.

--
Lance E Sloan, Application Developer
Univ. of Michigan, Info. and Tech. Services - http://www.its.umich.edu/
Cloud storage; get a 500MB bonus: https://db.tt/anbh6EW

**Comment by gryglbrt** [comment]
@lsloan Just so I'm not holding you up I restored the caliper branch. Once I get the development branch into a workable state we can discuss consolidating.

**Comment by lsloan** [comment]
:+1:

**Pull request merged**
